import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./resets.css";

import { Nav } from "@/components/layout/nav";
import { cn } from "@/utils/cn";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="tr">
			<body className={cn("bg-background min-h-screen font-sans antialiased", inter.variable)}>
				<Nav />
				<div className="p-1">{children}</div>
			</body>
		</html>
	);
}
